name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Check Python
        run: |
          make init
          make style

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Run unit tests
        run: |
          make test